In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('play_tennis.csv')

In [4]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [5]:
#P(Yes)
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [6]:
py=9/14
pn=5/14

In [7]:
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [8]:
pon = 0/5
prn = 2/5
psn = 3/5

poy = 4/9
pry = 3/9
psy = 2/9

In [9]:
#temp

pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [10]:
pcooln = 1/5
photn = 2/5
pmildn = 2/5

pcooly = 3/9
photy = 2/9
pmildy = 4/9

In [11]:
#humidity

pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [14]:
phighn = 4/5
pnormn = 1/5

phighy = 3/9
pnormy = 6/9

In [15]:
#wind

pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [19]:
pstrongn = 3/5
pweakn = 2/5

pstrongy = 3/9
pweaky = 6/9

In [22]:
#outlook=sunny temp=hot, Humidity=high, wind=weak

Pyes =  py * psy * photy* phighy * pweaky
Pyes

0.007054673721340388

In [25]:
Pno = pn* psn * photn * phighn * pweakn
Pno

0.02742857142857143

# No play