In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [5]:
df.shape

(100, 6)

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [8]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [9]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid'])
                                                 ,df['has_covid']
                                                ,test_size=0.2)

In [11]:
X_train

    age  gender  fever   cough       city
56   71    Male    NaN  Strong    Kolkata
42   27    Male  100.0    Mild      Delhi
61   81  Female   98.0  Strong     Mumbai
70   68  Female  101.0  Strong      Delhi
74   34  Female  104.0  Strong      Delhi
..  ...     ...    ...     ...        ...
50   19    Male  101.0    Mild      Delhi
47   18  Female  104.0    Mild  Bangalore
6    14    Male  101.0  Strong  Bangalore
7    20  Female    NaN  Strong     Mumbai
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [13]:
d=transformer.fit_transform(X_train)

In [15]:
dd = pd.DataFrame(d)

In [16]:
dd

             0    1    2    3    4    5     6
0   100.901408  1.0  1.0  0.0  1.0  0.0  71.0
1   100.000000  0.0  1.0  1.0  0.0  0.0  27.0
2    98.000000  1.0  0.0  0.0  0.0  1.0  81.0
3   101.000000  1.0  0.0  1.0  0.0  0.0  68.0
4   104.000000  1.0  0.0  1.0  0.0  0.0  34.0
..         ...  ...  ...  ...  ...  ...   ...
75  101.000000  0.0  1.0  1.0  0.0  0.0  19.0
76  104.000000  0.0  0.0  0.0  0.0  0.0  18.0
77  101.000000  1.0  1.0  0.0  0.0  0.0  14.0
78  100.901408  1.0  0.0  0.0  0.0  1.0  20.0
79  100.000000  1.0  0.0  0.0  1.0  0.0  11.0

[80 rows x 7 columns]